hardware/include/iob_lib.vh
- Fixed S2F_SYNC macro syntax to work for register widths that use a parameter
=> minor fix for S2F_SYNC using parameter as register width

hardware/include/iob_lib.vh
RESET_SYNC() macro uses source and destination signals to generate the auxiliar register.
This facilitates cases when the signal in the source clock domain is synchronized to multiple destination clock domains.
Example: to sync the `rst` signal from the `sysclk` domain to `clk_in` and `clk_out` domains we would do:
```
`RESET_SYNC(clk_in, rst, rst_in)
`RESET_SYNC(clk_out, rst, rst_out)
```
But previously this would lead to a synthesis error, since each macro would create an auxiliar register array:
`reg [1:0] rst_sync;`
with this change now the auxiliar register is unique:
`reg [1:0] rst_rst_in_sync;` and 
`reg [1:0] rst_rst_out_sync` respectively
This change has been tested in vivado
=> Improved RESET_SYNC macro

software/mkregs.py
- Only needed to execute as python3 all syntax is compatible
=> fix(python): Update mkregs.py to python3

hardware/hardware.mk
Hi,
iob_lib.vh has been added to VHDR. It was added yesterday after discussion with Joao and after its addition we will be able to see iob_lib.vh in VHDR in skywater Makefile
Kindly have a look at it 
regards,
=> Added iob_lib.vh to VHDR in hardware.mk so that it appears in VHDR 

hardware/iob2axi/Makefile, hardware/iob2axi/iob2axi_rd.v, hardware/iob2axi/iob2axi_tb.v, hardware/iob2axi/iob2axi_wr.v, hardware/iob2axi/waves.gtkw
"make sim-waves" in the iob2axi folder should run the simulation that passes successfully and produces the vcd where the signals follow the native interface correctly.
Didn't test on the board, only simulation, but eventually I'll need to use this on the ethernet module, after the DMA changes, and in that time I'll test it fully.
=> Added testbench and small fixes to iob2axi

software/include/iob-lib.h
- Update `iob-lib.h` macros to be function declaration for pc-emul case.
- Keep same behaviour as before for embedded drivers
=> feat(sw): _SET() _GET() macros are functions in PC

software/include/iob-lib.h
- Fix macros in iob-lib.h, some macro parameters where not inside parenthesis
- This could lead to weird bugs, for example with:
```C
// Old macro
#define IO_SET(base, location, value) (*((volatile int*) (base + (sizeof(int)) * location)) = value)
// Example Problematic usage
for(i=0; i<N; i++)
IO_SET(base, SOME_REG + i, new_val[i]);
// Expands to:
for(i=0; i<N; i++)
(*((volatile int*) (base + (sizeof(int)) * SOME_REG + i)) = new_val[i]);
```
- Notice how only `SOME_REG` gets multiplied by `sizeof(int)`, instead of the expected `sizeof(int) * ( SOME_REG + i)` behaviour.
- This leads to inconsistent access patterns.
- With the old macro the CPU would access a peripheral core:
```
- core[SOME_REG + 0] = new_val[0]
- core[SOME_REG + 0] = new_val[1]
- core[SOME_REG + 0] = new_val[2]
- …
```
=> fix(sw): Fix iob-lib.h macros

software/python/mkregs.py, software/python/verilog2tex.py
The advantage of "#!/usr/bin/env python" is that it will use whatever python executable appears first in the user's $PATH. Which could also be a disadvantage. But I think in our case it is not.
In other words, the advantage is that it turns the script more portable. The disadvantage is that if the python interpreter path isn't on the user $PATH the command may fail (not too likely on modern systems).
=> python enviroments compatability

software/include/iob-lib.h
- Declare functions in `iob-lib.h` as static
- This is needed so that each core drivers can have a different
implementation for the functions
- For example if we have a system with a TIMER and ETHERNET core each
peripheral has a implementation of the `IO_GET()` and `IO_SET()`
functions for the pc-emul case.
Declaring the functions as static allows for a different
implementation per peripheral.
This change restricts the usage of the
`MEM_SET()/MEM_GET()/IO_SET()/IO_GET()` macros/functions to the common
software driver code of each peripheral (software/iob-timer.c and
software/iob-eth.c for the timer and ethernet peripherals
respectively)
- This change also requires updating the embedded/pc-emul specific files
to a `iob-CORE-platform.h` file that is included in the common driver
file.
=> fix(sw): static function declaration for pc-emul

software/python/mkregs.py
The `hw_max_addr` needs to be incremented by 1 to include the register
with address "0" (The first register in the `table` list).
For example, without this fix, an error occurs trying to build a peripheral with only one register:
The register will have address 0, therefore `hw_max_addr` will be 0 and
`math.log(0,2)` will throw an error.
=> Fix bug in mkregs.py

document/document.mk, software/python/mkregs.py, software/python/verilog2tex.py
- Improve help / usage information
- `mkregs.py` requires `mkregs.conf` file instead of `CORE_swreg.vh` file
- refactor mkregs.py script
- these changes deprecate `CORE_swreg.vh` file and require `mkregs.conf` file for each peripheral
- need to update mkregs.py script calls
- need to remove infered usage  of `CORE_swreg.vh` files (mostly in iob-soc to generate `system.v` and `system_top.v`)
=> Refactor mkregs

software/python/mkregs.py
- Fix address block size for registers to always be a power of 2
- this is necessary when the number of registers is larger than all
other memories
=> fix(mkregs): addr block for regs is power of 2

software/python/mkregs.py
Line 346: 
The increment to hw_max_addr should be done outside the math.floor() function, this guarantees that hw_max_addr is at least 1.
Without this fix, an error occurs when max_addr is less than cpu_nbytes (for example in a peripheral with only one register), because the value of hw_max_addr would be 0 and causing math.log(0,2).
Line 348: 
The return value addr_w should be at least 1 bit wide, since it will be used to generate the ```"`define {regfile_name}_ADDR_W {get_core_addr_w(table, cpu_nbytes)}\n\n"``` (line 359) verilog macro, that can only be greater than zero.
Without this fix, when addr_w is zero (for example in a peripheral with only one register) (I will use a UART with only one register here as an example), the value used when calling the line …
=> Fix bug in 'mkregs.py' 

.github/workflows/ci.yml, Makefile
- Add Makefile to test memory modules
- based on [iob-mem original
Makefile](https://github.com/IObundle/iob-mem/blob/master/Makefile)
- Add github action to run memory tests
- Check `Makefile` header comment for usage
Usage:
- `make all`: run make test
- `make test`: simulate all memory modules with testbench files
- `make sim MEM_MODULE_DIR=<path/to/mem/module>`: simulation individual mem
=> feat(tests): Makefile for testing memory modules

Makefile, build/Makefile, build/doc/Makefile, build/hw/sim/Makefile, software/python/version.py
- add usage and minor fix to version format in `version.py` script
- LIB/Makefile:
- update copy order in setup target
- use `DOC_DIR`, add `build` target for documents
- move default `DOC` type to `build/doc/Makefile` to follow same
process as simulation and fpga
- move tests targets and `test.expected` to custom makefile segments
- current setup assumes that tests should be performed by comparing a `test.log` with a `test.expected` file 
- test.log comparison is not what we want in the general case
- remove copying `test.expected` from LIB/Makefile
- example for `fpga-run` targets:
- how to support multiple fpga top levels, for example? Currently all verilog source files are copied to the same folder and added as sources for synthesis
- Idea: create a separated build directory tree for …
=> feat(build): Minor improvements to build system

hardware/ram/iob_ram_2p_be/hardware.mk, hardware/ram/iob_ram_2p_be/iob_ram_2p_be.v, hardware/ram/iob_ram_2p_be/iob_ram_2p_be_tb.v
This ram component allows the `w_en` signal to select which bytes to write.
This component is required by iob_ram_2p_asym when using asymetric input/output (the `ext_mem_w_en` signal from that component has multiple bits).
=> Add iob_ram_2p_be verilog module

hardware/iob_split/iob_split.v, software/python/makehex.py
Added support for multiple files to makehex.py;
Usage: ./makehex.py 1st_File 2nd_File 2nd_File_addr ... Firmware_Size > output
The first file is the main file and its address is 0.
This PR was tested with the current iob-soc, and it works fine;
=> Removed iob-split unused msb of s_sel; Edited makehex.py;

build/sw/python/verilog2tex.py
- check TOP_MODULE and all other VSRCS for START_IO_TABLE and generate
interface tables accordingly
- for example iob-cache has two top modules that need parsing to
generate all interface signal tables
=> fix(verilog2tex): check all sources for IO table

Makefile, build/doc/Makefile, build/doc/tsrc/synth_lib.tex, build/doc/tsrc/ug.tex
- use deliverables_lib.tex if the IP core does not include a deliverables.tex file
- make Synthesis section optional
=> update documentation processing

setup.mk
- copy core makefile segments from CORE_DIR/harwdare/simulation/
directory into `BUILD_DIR_SIM`
- these files are used for simulation, namely `simulation.mk`
=> fix(setup): copy mk segments from CORE sim

setup.mk
- use `sim_setup.mk` makefile fragment to check for specific VSRC and
VHDR files related to core simulation
- copy core's `simulation.mk` makefile fragment if exists. Only this
makefile fragment is imported in `BUILD_SIM_DIR/Makefile`
=> fix(setup): rename sim_setup.mk

build/hw/sim/Makefile, build/sw/emb/Makefile, build/sw/pc/Makefile, setup.mk
- Add option to use `config_setup.mk` makefile fragment with custom CORE targets and variables during `setup`
- Add option to use `config.mk` makefile fragment with custom CORE targets and variables for BUILD_DIR makefiles
=> Optional usage of `config_setup.mk` and `config.mk`

build/hw/sim/Makefile, build/sw/pc/Makefile, hardware/iob_edge_detect/hardware.mk, hardware/iob_modcnt/hardware.mk, hardware/iob_reset_sync/hardware.mk, hardware/iob_reset_sync/iob_reset_sync.v
- PC macro/define is not always necessary
- define PC in `pc-emul.mk` if needed
- add `NOCLEAN` variable to customize simulation clean target
- this allows the usage of `BUILD_LIB/hw/sim` directory to place
simulation specific sources without being deleted
=> Remove PC macro, add `NOCLEAN` variable for exceptions

setup.mk, software/python/version.py
- improve version script to implement 3 distinct functionalities:
1. generate verilog header file with VERSION
2. generate latex header file with VERSION
3. print VERSION to stdout
- check `software/python/version.py --help` for more details
- update `version.py` usage in `setup.mk`
- update `setup.mk` to optionally include `doc_setup.mk`
- move version file generation to respective `hardware.mk` or
`doc_setup.mk` files
=> fix(version): improve version script, update setup

build/sw/pc/Makefile, hardware/iob_clkbuf/hardware.mk, setup.mk
- update setup to only copy specific sw, sim, fpga and doc folders to
BUILD_DIR is specific folders are present in the CORE repository
- remove SETUP_XYZ variables
- only try to copy .expected files if they exist
- fix(iob_clk): fix target name
=> Setup depends on core folders, minor improvements

software/python/mkregs.py
- catch `NameError` exception on `header_parse` function
=> Fix documentation header_parse function

document/tsrc/pb.cls
- pb.cls was adding ../figures to graphicspath, now should be ./figures, like in ug.cls
=> fix(doc): correct path to figures dir

scripts/createSystem.py, scripts/createTestbench.py, scripts/createTopSystem.py, scripts/submodule_utils.py
- get_submodule_directories() in `submodule_utils.py` now parses the `config_setup.mk` file located on the root_dir, finding every variable defined ending with "_DIR".
- Removed directories_str parameter, as it is no longer needed.
- Remove root_dir global variable from submodule_utils.py; Use local root_dir variables instead.
=> Get peripheral directories by parsing config_setup.mk

build.mk, setup.mk, software/pc-emul/Makefile
- Update pc-emul support, tested for iob-soc
- set `software/pc-emul` as directory for pc-emul BUILD_DIR
- fix/add some BUILD_<PATH>_DIR variables related to pc-emul
- automate LIB/software/pc-emul file copy during setup (if `CORE/software/pc-emul` exists)
- update pc-emul Makefile
- clean generated C header source files
=> PC-Emul support

setup.mk
- remove conf.vh verilog header generation from LIB, each core should generate or copy its own configuration as needed
=> fix(setup): remove conf.vh generation from LIB

build.mk, hardware/fpga/Makefile, scripts/mkregs.py, setup.mk, software/embedded/Makefile, software/pc-emul/Makefile
- Improvements to embedded software workflow
- update embedded workflow to compile bootloader and firmware programs
for embedded platform
- import console.mk if exists, used to `kill-cnsl` target in pc-emul and
fpga makefiles
- embedded bootloader compilation working
- fix example in help message for `mkregs.conf`
=> Improvements to embedded software workflow, mkregs help message

scripts/mkregs.py
- update mkregs.py to generate SW accessible registers according to new
IOb interface
- the new IOb interface uses a subset of AXI4-Lite signals:
- valid
- addr
- wdata
- wstrb
- rdata
- rvalid
- ready
- refactor mkregs.py code to be more reusable
- script still needs more testing and validation
- exit mkregs.py script if registers are missaligned
- downgrade overlapped registers to print warning only
=> mkregs.py: support new IOb interface, improve error checking

scripts/mkregs.py, scripts/test_mkregs/alignedreg_mkregs.conf, scripts/test_mkregs/autoaddr_mkregs.conf, scripts/test_mkregs/out_of_order_addr_mkregs.conf, scripts/test_mkregs/overlapped_mkregs.conf
- mkregspy calculated new aligned addresses for registers with automatic
addresses (ADDR<0)
- add `mkresg.conf` to test automatic addressing in
`scripts/test_mkregs/`
- other minor improvements to mkregs.py
- support declaration of out of order registers in `mkresgs.conf`
- `scripts/test_mkregs/out_of_order_addr_mkregs.conf`: test register
declaration out of order
- automatic addresses start after the largest manual address
- check for aligned registers:
- `scripts/test_mkregs/alignedreg_mkregs.conf`: test register
alignment (expected catch register miss aligment)
- check for overlapped register ranges
- `scripts/test_mkregs/overlapped_mkregs.conf`: test register
range overlapping (expected to catch resgister arrays with
overlapping)
Supporting declaration of registers with out of order …
=> feat(mkregs): improve address support; add example `mkregs.conf` to test

hardware/include/hw_setup.mk, mkregs_example.toml, scripts/mkregs.py, scripts/verilog2tex.py, setup.mk
Implement changes mentioned in https://github.com/IObundle/iob-lib/issues/240.
Add `mkregs_example.toml` example file in root directory of LIB.
Rename `mkregs.conf` to `mkregs.toml`.
This PR closes https://github.com/IObundle/iob-lib/issues/240.
=> Update mkregs.conf to use TOML configuration format

software/python/console, software/python/noncanonical.py
The `getUserInput` function is launched as a thread when the console receives a `DC1` Byte;
The `noncanonical.py` file is a temporary solution to the Linux user input. It works, but it is not the best solution. The best solution would be to execute a terminal emulator in the Console program.
=> Add feature: support Linux OS; Fix: transferred orthography;

hardware/include/iob_lib.vh
- remove duplicated macrom from iob_lib.vh verilog header file
=> fix(hw): remove duplicated IOB-LIB macro

scripts/ios.py, scripts/setup.py
- Add _ios.py_ script
- Update _setup.py_ to use functions from _ios.py_.
_ios.py_ is a script to generate the _io.vh_ file with Verilog module IO definitions based on the `<corename>_setup.py` configuration file. It also has functions to generate the TeX tables with port descriptions.
=> feat(ios.py): add ios.py script

scripts/mkregs.py, scripts/setup.py
The problem with calling the mkregs function multiple times in setup.py is that the first time it was called, it altered the original registers table. The second time mkregs was called, it was trying to alter the register's table again on top of the already altered table.
=> Fix passing the regs table when calling HW and SW mkregs functions;

scripts/if_gen.py, scripts/ios.py
- Modify _ios.py_ and _if_gen.py_ to use Verilog `input`, `output`, and `inout`, instead of `IOB_` macros.
- Remove last comma of generated io.vh
=> feat(IOs): use normal Verilog IO instead of IOB_ macros

scripts/setup.py
- Allows configuring if read/write register addresses should overlap
- Closes https://github.com/IObundle/iob-lib/issues/263
=> feat(setup.py): Add no_overlap argument

document/Makefile, document/tsrc/config.tex, document/tsrc/swreg.tex, hardware/simulation/icarus.mk, scripts/ios.py, software/embedded/Makefile, software/pc-emul/Makefile
- Fix documentation makefile segments
- Fix column in longtable
- Make swreg optional by checking if there are any *_swreg_tab.tex files. The 'swreg.tex' file is always copied by 'setup.mk' if it doesn't exist.
- Include sources from the firmware source directory, the same way it is done in the embedded firmware Makefile.
- Fix firmware and boot LFLAGS
=> feat(doc,sw): fix bugs; fix firmware and boot LFLAGS

hardware/fpga/Makefile, hardware/simulation/verilator.mk, scripts/console.py, software/pc-emul/Makefile
- Rename console file to console.py
- Add CFLAGS to include embedded headers for simulation testbench.
- Add very-clean target. This target is required for simulation (called from simulation Makefile).
=> feat(console;verilator): rename console script to console.py; include embedded sources.

scripts/mkregs.py
- The new implementation of this function uses a regex expression to replace exact macro/parameter names by their max value.
- It always replaces the macro/parameter name by its max value to account for the worst-case scenario.
- It will not wrongly replace "TX_ADDR_W" by the value of "ADDR_W" even though its name is cotained in the string.
=> feat(mkregs): update compute_n_bits_value() function

document/tsrc/sw.tex, document/tsrc/ug.tex, scripts/mkregs.py
- Add conditional operator to the IOs of swreg modules to ensure signal widths are greater than zero.
- Remove _sw.tex_ file. Include its contents in the _swreg.tex_ file generated by _mkregs.py_
=> feat(mkregs,doc): Add ternary operator to mkregs IO; Remove sw.tex.

software/python/console
The current `console` script hardcodes the serial port to `/dev/usb-uart`.
From my testing, the script has an argument to provide that (`-s`).
This PR replaces the hardcoded value to the one provided by the user argument.
=> Fixed console serial port declaration

hardware/fpga/Makefile, hardware/fpga/quartus/CYCLONEV-GT-DK/board.mk, hardware/fpga/quartus/CYCLONEV-GT-DK/device.tcl, hardware/fpga/quartus/build.tcl, hardware/fpga/quartus/quartus.mk, hardware/fpga/vivado/build.tcl, hardware/fpga/vivado/vivado.mk, scripts/mk_configuration.py
- Add target to build `alt_ddr3.qip` for CYCLONEV.
- Rename 'RUN_EXTMEM' to 'USE_DDR' for FPGA related components, as they may be used in other cores that do not necessarily run from external memory.
- Add settings for BASYS3 and DE10-LITE.
=> Add target to build `alt_ddr3.qip` for CYCLONEV 

scripts/build_srcs.py, scripts/tester.py
- Specify which type of script to add as a lambda function ('sim_setup','fpga_setup' or 'sw_setup'). This prevents duplicate  lambda functions in the same lists. It fixes issue that was causing `fpga_setup.py` to be called multiple times.
- Remove unused 'uut_name' tester option.
=> Specify lamba function types during setup; Remove unused `uut_name` tester option.

hardware/fpga/quartus/build.mk, hardware/fpga/quartus/build.tcl, nix/riscv-gnu-toolchain.nix, nix/shell.nix, scripts/build_srcs.py, scripts/createSystem.py, scripts/createTopSystem.py, scripts/mk_configuration.py, scripts/mkregs.py, scripts/setup.py, scripts/submodule_utils.py, setup.mk
- Clean 'sopc_altera_pll*' folders generated in home directory. Related to issue IObundle/iob-soc#519
- Fixed `riscv-gnu-toolchain.nix`. This toolchain now compiles correctly in Nix sandbox environment.
- Update import_setup() function to allow setting arbitrary variables before executing imported module.
- Update software generation in `setup.py`. Now, the `esrc` and `psrc` folders will be built even if they don't exist in the setup dir.
- Prevent exporting SETUP_ARGS. This way recursive calls to makefile won't append to existing SETUP_ARGS list.
- Update 'int' variable type detection in functions of mkregs.py
- Rename iob-soc pragmas. Related to issue IObundle#430
=> Update `riscv-gnu-toolchain.nix`; Update import_setup() function; Clean 'sopc_altera_pll*' folders.

software/prng/xoshiro256plusplus/example/Makefile, software/prng/xoshiro256plusplus/example/example_xoshiro.c, software/prng/xoshiro256plusplus/iob_xoshiro256plusplus.c, software/prng/xoshiro256plusplus/iob_xoshiro256plusplus.h
- add example implementation for xoshiro256++ PRNG
- this implementation uses splitmix64 for initialization
- more information [here](https://prng.di.unimi.it/)
- add example in software/prng/xoshiro256plusplus/example
- run example with:
```
make -C software/prng/xoshiro256plusplus/example all
make -C software/prng/xoshiro256plusplus/example clean
```
=> feat(PRNG): implementation for xoshiro256++

hardware/simulation/verilator.mk
- Remove verilator --timing flag, as it is not working as intended. Verilator still throws errors with this flag when running a module with the `IOB_CLOCK` macro. Removing this flag also allows using older versions of Verilator.
=> feat(revert): Revert commit bfd895f9: Remove verilator --timing

hardware/fpga/Makefile, hardware/fpga/vivado/build.mk, hardware/fpga/vivado/build.tcl
- The `GRAB_CMD` command in the hardware/fpga/Makefile would only print a message and would not wait if a board was busy. 
This commit adds a loop to wait while the board is busy, trying again every 10 seconds.
- Create reports folder before running vivado.
=> Fix `GRAB_CMD` command in fpga/Makefile.

scripts/board_server.py
- fix board server to prevent user_name overwrite in grabbed state.
- Now, `user_name` is only set if grab request is accepted
- Example scenario: 
0. server is idle
1. `./board_client grab userA` // User A grabs board, status = grabbed
2. `./board_client grab userB` // User B tries to grab board, request is denied, but `user_name` is set to `userB`!
3. `./board_client release userA` // User A tries to release board, but since `user_name` does not match `released_user_name`, the request is denied
- update board busy message to reflect correct server expectations: the
client should make a new grab request at a later time
=> fix(board server): prevent user overwrite

hardware/fpga/Makefile, hardware/simulation/Makefile, software/pc-emul/Makefile
- Modify `test` targets in makefile segments to compare the `test.log` file contents with the string `Test passed!`. If it matches, then the test was successful, otherwise it throws an error. The `test.expected` files are no longer used.
=> Compare with "Test passed!" string instead of using `test.expected` file

scripts/board_client.py, scripts/board_server.py
- update board_client to set `USER` from environment. This stops any user
from releasing or grabing the board using another username
- update board_server to check for existing username value in received
message. Send `missing username` message as response.
- add optional `timeout` when grabbing board (set in seconds)
- improve grab timeout accounting in board_server:
- check for timeout every second (accept and recv operations timeout
every 1 second, each server loop iteration checks for grab timeout)
- by default `grab_timeout` is 300, like previous version
**NOTE: update `board_server` deployments after accepting this PR**
=> Board scripts: improve USER handling and grab timeout

Makefile, hardware/fpga/Makefile, hardware/fpga/quartus/build.mk, hardware/lint/alint.mk, hardware/lint/spyglass.mk, hardware/simulation/Makefile, hardware/simulation/verilator.mk, hardware/syn/Makefile, scripts/black_format.py, scripts/blocks.py, scripts/board_client.py, scripts/board_server.py, scripts/build_srcs.py, scripts/clang_format.py, scripts/clang_install.py, scripts/console.mk, scripts/console.py, scripts/if_gen.py, scripts/joinHexFiles.py, scripts/mkregs.py, scripts/submodule_utils.py, scripts/verilog2tex.py, software/Makefile
**Note**: This PR upgrades the `board_client.py` and `board_server.py` to the version `0.2`. Only the  `board_client.py` has changes, but the communication protocol is the same. The version of the `board_server.py` was only upgraded to prevent version mismatch errors with the new `board_client.py`. The new `board_server.py` should be installed on the machines that share FPGA boards.
The FPGA checks in https://github.com/IObundle/iob-soc/pull/546 have not yet passed, as the new `board_server.py` has not been installed in those machines. Once installed, the FPGA checks should pass.
**Changelog**
- Re-add verilator `--timing` flag as it is required for opencryptolinux. This reverts commit 56eabd0.
- Remove diff with `test.expected` file and instead compare with `Test passed!` string.
- This …
=> Upgrade `board_client.py` to replace Makefile handling and `trap` commands.

hardware/simulation/Makefile, scripts/board_client.py, scripts/submodule_utils.py, setup.mk
- Copy `.vcd` file from remote machine after interrupt signal with `VCD=1`
- Modify `clean` target in `setup.mk` to ignore errors when running `make -C $(BUILD_DIR) clean`. 
The previous `clean` target would throw errors if the setup function did not run correctly or was incomplete. By ignoring the errors, the incorrectly set-up build directory can still be cleaned (removed).
- Update `board_client.py`:
- Modify `board_client.py` to exit with code 0 if terminated due to interrupt/terminate signal.
- Fix timeout bug in `board_client.py`
- Add an error message in `board_client.py` with instructions to add search path for the `iob_colors.py` module.
- Update `submodule_utils.py`:
- Remove synchronous reset signals from reserved signals list in `submodule_utils.py`
- Add option in …
=> Copy `.vcd` file from remote machines; Update `board_client.py` and `submodule_utils.py`; Update `clean` target.

scripts/board_client.py
Remove `-S` flag from the `env` program in the shebang line. Not every `env` program supports this flag.
This is the implementation of the suggestion I left in https://github.com/IObundle/iob-lib/pull/488.
=> Remove `-S` flag from `env` program in `board_client.py`

setup.mk
- add python-format check to setup target
- add python-format target to LIB/setup.mk
- top level can use `make python-format` to format repository code
- currently only supports python
- closes iobundle/iob-lib#494
=> Python format for setup

scripts/verilog_tools.py, setup.mk
- Fix bug replacing includes;
- Format Verilog headers files along with sources;
- Update `verilog_tools.py` to only replace include statements inside the Verilog modules. It no longer replaces the include statements at the start of the file, outside the module. Related to https://github.com/IObundle/iob-lib/issues/491
=> Only replace includes inside Verilog modules; Fix bug; Format Verilog headers.

nix/shell.nix, setup.mk
- add c-format-check and c-format targets
- add format-check-all target to combine python, c and verilog format checks
- add llvm/clang dependency to nix-shell file, used for clang-format
- addresses iobundle/iob-lib#497
=> feat(setup): add c-format targets

nix/shell.nix
- By using version 14 instead of 15, we don't need to manually change the Nix configuration to use unstable packages.
=> feat(nix): Downgrade `llvmPackages` version to 14.

scripts/verilog_tools.py
- Update `replace_includes()` function to replace `include` statements:
- Recursively;
- Inside instances of modules as well. Not just inside module definitions.
=> feat(verilog_tools): Replace includes in Verilog files recursively.

scripts/verilog_tools.py
- Update `replace_includes_in_code()` function to replace every `include` statement from the contents of files that have already been included.
- Remove parse for Verilog instances.
- Parse for `endmodule` keyword to prevent replacing includes after the module's finish.
When a file is processed by this script and it is not being included into another one, then only the `include` statements that are inside a Verilog module are replaced.
If the file being processed is being included in another one, then every `include` statement of this file will be replaced.
=> feat(verilog_tools): Replace every `include` from already included files. 

hardware/modules/iob_tasks/iob_tasks.vh, scripts/verilog_tools.py
- Delete files after including their contents in all the other files that need them.
- Allow inclusion of duplicate files. 
Note: This assumes that files included inside modules always have the same contents. If there are multiple files with the same name in the build directory, and they are included inside a Verilog module, then all those files must have the same contents, otherwise errors will occur. The `verilog_tools.py` script will insert the contents of the first file found with this name (it assumes the others with the same name also have the same contents).
=> [verilog_tools.py] Delete files after including them; Include files with duplicates in build dir.

hardware/modules/axis2axi/axis2axi_in.v, hardware/modules/axis2axi/axis2axi_out.v, hardware/modules/axis2axi/axis2axi_tb.v, hardware/modules/counter/iob_modcnt/iob_modcnt.v, hardware/modules/fifo/iob_fifo_async/iob_fifo_async_tb.v, hardware/modules/fifo/iob_fifo_sync/iob_fifo_sync.v, hardware/modules/fifo/iob_fifo_sync/iob_fifo_sync_tb.v, hardware/modules/iob2axi/iob2axi_rd.v, hardware/modules/iob2axi/iob2axi_tb.disable.v, hardware/modules/iob_asym_converter/iob_asym_converter_tb.v, hardware/modules/iob_ctls/iob_ctls.v, hardware/modules/iob_split/iob_split.v, hardware/modules/ram/iob_ram_2p/iob_ram_2p_tb.v, hardware/modules/ram/iob_ram_2p_be/iob_ram_2p_be_tb.v, hardware/modules/ram/iob_ram_2p_tiled/iob_ram_2p_tiled_tb.v, hardware/modules/ram/iob_ram_dp/iob_ram_dp_tb.v, hardware/modules/ram/iob_ram_dp_be/iob_ram_dp_be_tb.v, hardware/modules/ram/iob_ram_dp_be_xil/iob_ram_dp_be_xil_tb.v, hardware/modules/ram/iob_ram_sp/iob_ram_sp_tb.v, hardware/modules/ram/iob_ram_sp_be/iob_ram_sp_be_tb.v, hardware/modules/ram/iob_ram_t2p/iob_ram_t2p_tb.v, hardware/modules/ram/iob_ram_tdp/iob_ram_tdp.v, hardware/modules/ram/iob_ram_tdp/iob_ram_tdp_tb.v, hardware/modules/ram/iob_ram_tdp_be/iob_ram_tdp_be_tb.v, hardware/modules/regfile/iob_regfile_dp/iob_regfile_dp.v, hardware/modules/regfile/iob_regfile_dp/iob_regfile_dp_tb.v, hardware/modules/regfile/iob_regfile_sp/iob_regfile_sp_tb.v, hardware/modules/rom/iob_rom_dp/iob_rom_dp_tb.v, hardware/modules/rom/iob_rom_sp/iob_rom_sp_tb.v, hardware/modules/rom/iob_rom_tdp/iob_rom_tdp_tb.v
- fix `$finish()` and `$fatal()` macros in testbenches
- format some verilog files
- there are still verilog files with problems
=> format some verilog files

hardware/modules/axis2axi/AxiDelay.v, hardware/modules/axis2axi/axis2axi_in.v, hardware/modules/axis2axi/axis2axi_out.v, hardware/modules/iob2axi/iob2axi.v, hardware/modules/iob2axi/iob2axi_rd.v, hardware/modules/iob2axi/iob2axi_wr.v, hardware/modules/iob_demux/iob_demux.v, hardware/modules/iob_lib.vh, hardware/modules/iob_merge/iob_merge.v, hardware/modules/iob_mux/iob_mux.v, hardware/modules/iob_prio_enc/iob_prio_enc.v, hardware/modules/iob_split/iob_split.v, hardware/modules/ram/iob_ram_2p_tiled/iob_ram_2p_tiled.v, hardware/modules/ram/iob_ram_tdp/iob_ram_tdp.v, scripts/shell.nix
- notice that iob2axi.v and iob_merge.v can't pass verilog format due to
processing macros with arguments (probably related with this issue:
https://github.com/chipsalliance/verible/issues/1524)
- add libreoffice to nix shell environment, needed by document flow
- some verilog source linting
=> format verilog files, add libreoffice to nix, lint verilog sources

hardware/modules/axis2axi/axis2axi_in.v, hardware/modules/axis2axi/axis2axi_out.v, hardware/modules/iob2axi/iob2axi.v, hardware/modules/iob_merge/iob_merge.v
- revert axi2axil always_comb blocks to pass LIB tests
- need to review always @* processes more closely to convert to
always_comb
- add missint includes to iob_merge and iob2axi
=>  fix(test): revert axi2axil always_combs 

hardware/modules/iob_clkbuf/iob_clkbuf.v, hardware/modules/iob_clkmux/iob_clkmux.v, hardware/modules/iob_iobuf/iob_iobuf.v, scripts/verilog-format.sh, setup.mk
@jjts Please check changes before accepting. 
There are changes that were imported from a pull, however they are not currently in the upstream repositor.
=> setup.mk, verilog-format.sh: find all .v, .vt and .vh; fix not to through an error when no files are passed

hardware/modules/iob2apb/iob2apb.py, hardware/modules/iob_clkbuf/iob_clkbuf.py, hardware/modules/iob_clkmux/iob_clkmux.py, scripts/bootstrap.py, scripts/build_srcs.py, scripts/iob_module.py, scripts/setup.py
- Add missing python modules. 
- Set correct permissions in files copied during setup. 
- Only auto-append VERSION macros/regs if they don't exist already.
- Copy files from `syn` and `lint` directories  when running `_copy_srcs() `
=> Object oriented

hardware/fpga/Makefile, hardware/fpga/vivado/build.mk, hardware/fpga/vivado/build.tcl, scripts/build_srcs.py, scripts/iob_module.py, scripts/setup.py, scripts/submodule_utils.py
This PR includes changes required for modifications in PR https://github.com/IObundle/iob-soc/pull/564
- Update reserved signals for ext_mem.
This will **break** iob-soc based systems using ext_mem that do not have the changes from https://github.com/IObundle/iob-soc/pull/564
- Add `N_INTERCONNECT_SLAVES` parameter to Vivado tcl scripts and Makefiles.
- Copy LIB files before repository sources.
Now, the `_run_setup()` method of the `iob_module` manages the copy sequence. The LIB files are copied first, followed by the copy of repository files.
- Only copy `hardware/src` and `software` directories from submodules.
No longer copies `hardware/simulation`, `hardware/fpga`, `hardware/lint`... from submodules.
=> Update extmem reserved signals; Fix order of file copy during setup; Only copy `hardware/src` and `software` from submodules.

scripts/build_srcs.py, scripts/iob_module.py, scripts/setup.py
Cherry-picked commit 6c70fee032c34103e0961c92dc602c7a15b4370f from python-setup branch.
- Change order of file copy during setup process; Previously, the files from the repo were copied first, and then the `setup()` function of LIB copied the LIB files and overriden files any in the build_dir. Now, `_run_setup()` method of the `iob_module` manages the copy sequence. The LIB files are copied first, followed by the copy of repository files.
- Only call *_setup.py files from the repo after copying every file from LIB and repo.
- Only copy `hardware/src` and `software` directories from submodules. No longer copies `hardware/simulation`, `hardware/fpga`, `hardware/lint`... from submodules.
=> Copy LIB files before repository sources.

scripts/submodule_utils.py, scripts/verible-lint.rules, scripts/verilog-lint.sh, setup.mk
[e7c5eb8]: Improve combined file. 
This commit improves the combined file generated.
- The new combined file will have the original file names inside comments separating the file contents.
- The new combined file won't be deleted if there is an error to allow analyzing its contents.
- The new combined file is "~linter_files_combined.tmp". This naming scheme follows one of the conventions mentioned here: https://docs.storagemadeeasy.com/incompatiblecharacters
[7372282]: Parse error message to print original file name. 
This commit improves the error messaged printed by the `verilog-lint.sh` script.
- Error messages of the combined file are now parsed and auto-converted to the original file name and line number that contains the error.
[3d7b06b]
This commit merges the upstream and fixes …
=> Improve `verilog-lint.sh` script.

hardware/modules/div/iob_div_pipe/iob_div_pipe.py, hardware/modules/div/iob_div_pipe/iob_div_pipe.v, hardware/modules/div/iob_div_pipe/iob_div_pipe_tb.v, hardware/modules/div/iob_div_pipe/iob_div_slice.v, hardware/modules/div/iob_div_subshift/iob_div_subshift.py, hardware/modules/div/iob_div_subshift/iob_div_subshift.v, hardware/modules/div/iob_div_subshift/iob_div_subshift_tb.v, hardware/modules/div/iob_div_subshift_frac/iob_div_subshift_frac.py, hardware/modules/div/iob_div_subshift_frac/iob_div_subshift_frac.v, hardware/modules/div/iob_div_subshift_frac/iob_div_subshift_frac_tb.v, hardware/modules/div/iob_div_subshift_signed/iob_div_subshift_signed.v, hardware/modules/regfile/iob_regfile_sp/iob_regfile_sp_tb.v, scripts/verilog-lint.py, setup.mk
- update regfile_sp instantiation in testbench
- fixes LIB CI flow 
- format `verilog-lint.py` script
- improve format targets: only run formater on BUILD_DIR if directory
exists. This allows to run `make python-format` target as standalone
even without running `make setup` or creating BUILD_DIR
- add divisor modules to lib
- subshift, subshift_frac, subshift_signed and pipelined versions
- modules and testbenches taken from IObundle/iob-div repository
=> fix LIB tests, improve format targets, format python script, add div modules

hardware/simulation/Makefile, scripts/mk_configuration.py
- Add function in `mk_configuration.py` to insert generic strings into `config_build.mk`.
- This function is useful to set build time configuration, such as changing the default simulator by inserting the string `SIMULATOR:=verilator` into the `config_build.mk`.
- Update simulation `test` target to be similar to the FPGA. 
- This change makes the simulation `test` target run targets from the `$(TEST_LIST)` in a similar way to the FPGA `test` target.
- In relation to the problem raised by this comment:
```
```
This problem should be solved by the targets inside the `sim_build.mk` file.
If there are too many ssh connections, then we should update the target inside the `sim_build.mk` file to only make one connection and then run the various commands/tests inside that single connection.
=> Update simulation `test` target; Update `mk_configuration.py`.

hardware/modules/div/iob_div_subshift/iob_div_subshift.v
- store divisor value on `start_i` instead on using direct input port by default
- this fixes problems when `divisor_i` changes in the middle of division operation
- replicates `dividend` logic
=> fix(div): fix div module

hardware/modules/iob_s2f_sync/iob_s2f_sync.py, hardware/modules/iob_s2f_sync/iob_s2f_sync.v
- update s2f_sync module to use `iob_sync` instance
- this enables usage of constraints for vivado tools like:
```
set_property ASYNC_REG TRUE [get_cells -hier {*synchronizer*[*]}]
set_property ASYNC_REG TRUE [get_cells -hier {*signal_o*[*]}]
```
- previous implementation used regular `iob_reg`.
=> feat(s2f_sync): update s2f_sync module

scripts/iob_module.py
This allows us to configure what is the highest superclass to copy sources from.
For example, if we only want to copy sources from the lowest subclass, then we can pass that subclass in this parameter. With this, only the sources from that subclass will be copied, since it will be both the lowest subclass and the highest superclass.
=> feat(_copy_srcs): Add parameter to select `highest_superclass`.

hardware/modules/iob_and/hardware/src/iob_and.v, hardware/modules/iob_aoi/hardware/src/iob_aoi.v, hardware/modules/iob_or/hardware/src/iob_or.v, hardware/modules/iob_xor/hardware/src/iob_xor.v
While running the `test.sh` script manually for the iob_aoi module, I noticed these syntax errors.
I'm still getting warnings like this `../src/iob_and.v:18: warning: and_vec[1+:1] is selecting after vector.` in both `iob_and` and `iob_or` and I suspect `iob_xor` suffers form the same problem.
I'm currently working on those.
=> Fixing errors shown by iverilog

scripts/iob_module.py
- remove remaining iob_verilog_instance references
- `iob_verilog_instance` was removed in IObundle/iob-lib#625
=> fix(iob_module): iob_verilog_instance references

scripts/mkregs.py
Address range added on *_swreg_gen.v instead of equality check (range of the array) and getter address corrected by removing the shift.
The correction also consequently changes the address check of other registers to include range check instead of equality check.
=> Correction in addressing for log2_items != 0

.gitignore, hardware/modules/iob_demux2/hardware/iob_demux2.v, hardware/modules/iob_demux2/iob_demux2.py, hardware/modules/iob_split/hardware/src/iob_split.v, hardware/modules/iob_split/iob_split.py, scripts/submodule_utils.py
Corrected a bug in submodule_utils.py and another one in iob_split.py. The latter happened because 3 signals were not being distributed to all the followers - only to the first one.
To correct that bug, demux2 was added, working the same way as iob_mux - by storing the signals into a register instead of just assigning wires.
=> Correct bugs and add iob_demux2

hardware/fpga/Makefile
- append to VHDR variable instead of overwriting in fpga/Makefile - previously VHDR variable was potentially ignoring values set in `fpga_build.mk`
=> fix(fpga): remove VHDR overwrite

scripts/mkregs.py
- update swreg instantiation to use internal wires for iob interface
- regular cores should have AXIL, APB or other standard interface/ports
and use a CSR_IF -> IOb converter
- removes _i and _o sufixes from iob native wires
=> feat(swreg): update swreg instantiation

hardware/modules/iob_pulse_gen/hardware/simulation/src/iob_pulse_gen_tb.v, hardware/modules/iob_pulse_gen/hardware/src/iob_pulse_gen.v
- update iob_pulse_gen:
- register output
- compensate extra cycle for output register for cases when `START > 0`: 
- when START > 1, output is enabled START cycles after `start_i == 1`. 
- When `START = 0`, output is enabled 1 cycle after `start_i == 1`
- update testbench for pulse_gen, checks for duration and start
=> feat(pulse_gen): register output, testbench

scripts/netlist_proc.py
- add python script to rename modules in netlist from <module name> to  <prefix><module name>
- this avoids module re-definitions when a module is used by TESTER system and core netlist
- add optional argument for custom prefix. `_` by default. This enables usage of different prefixes for each netlist to avoid colisions between netlists
=> feat(python): netlist processing script

hardware/fpga/quartus/build.tcl, hardware/fpga/quartus/timing.tcl
- timing.tcl: do not use NAME variable (was adding -report_script prefix to all reports)
- build.tcl: add core name prefix to all reports
=> fix(quartus): improve quartus report names
