hardware/include/iob_lib.vh
- S2F_SYNC has reset value
- added F2S_SYNC macro for improved code readability
=> Updated Synchronizer macros

hardware/include/iob_lib.vh
Cadence tools do not support string concatenation with ``
=> Added synchronization macro versions for ASIC synthesis

hardware/include/iob_lib.vh
- PISO macros now only read IN on LD
=> fix(macros): fix PISO macros

document/document.mk, document/ug/sw.tex, document/ug/ug.tex
- Remove software function subsection
- Update Section to indicate Software Accessible Register information
=> feat(doc): Update Software Drivers Section

software/python/mkregs.py
- Apply swmem commits after IObundle/iob-lib master branch
- We can delete IObundle/iob-lib swmem branch after merging this PR
=> Rebased swmem Branch into master branch

software/python/mkregs.py
- ignore 2 least significant bits in address from cpu
=> fix(mkregs): refactor cpu address in hardware

software/python/version.py
Please let me know if it is different from what you expected.
=> version.py update

software/python/mkregs.py
- fix cases where the memories take less than 1 CPU addressing bit:
- don't generate `NAME_addr` signal for memories that take a single CPU address
- `calc_mem_addr_w` checks for number of CPU addresses that take to address the complete memory data. This value should never be less that 0.
=> fix(mkregs): fixes for small memories

software/python/mkregs.py
- remove rdata register after selecting rdata from SWREGs
- register address and select rdata in the next cycle
- the core developer needs to ensure that the correct rdata is available
on the cycle after the valid signal
- this allows for a seemless interface for FIFO read data using a read
register
- see IObundle/iob-axis-in#4 for more details about using SWREG_R for
FIFO reads
=> fix(mkregs): remove register after rdata switch

build/doc/Makefile, build/doc/tsrc/if.tex, build/doc/tsrc/pb.cls, build/doc/tsrc/pb.tex, build/doc/tsrc/swreg.tex, build/doc/tsrc/ug.cls, build/hw/sim/Makefile
- fix version issue
- fix simulation Makefile issue
- generate pb.pdf even if the ip core does not have any tex files
- update cls files
- update some generic tex files
=> update documentation generation processing

setup.mk
- info.mk generation overrides NAME variable
=> fix(setup): info.mk missing NAME

scripts/createSystem.py, scripts/createTestbench.py, scripts/createTopSystem.py, scripts/submodule_utils.py, setup.mk
- File generating functions now receive a 'file_path' argument with path and name of file to be generated.
- Replace 'TOP_MODULE' by 'NAME'
- Add BUILD_SW_PYTHON_DIR in setup.mk
=> Update python scripts; Add BUILD_SW_PYTHON_DIR.

scripts/mkregs.py
- update mkregs to generate only required logic for outputs: 
- generate switch only if REG and MEM logic exists 
- if only one of REG or MEM types exist, assign output to existing logic 
- if no logic exists, assign output to 0
=> feat(mkregs): improve output logic generation

scripts/mkregs.py
- add read enable for read registers
- rename write enable signal for write registers
=> feat(mkregs): add read enable for read registers; rename write enable

scripts/verilog2tex.py
- update header parsing code: previous version was not reading .vh files
- refactor param parse function to use named fields
- closes #239
=> fix(verilog2tex): header parsing working again

Makefile, hardware/simulation/Makefile
- update axi_gen to if_gen
- simulation makefile respects NOCLEAN variable
=> fix(make): update if_gen script, NOCLEAN for sim

hardware/include/iob_lib.vh, scripts/if_gen.py
- re-add IOB_VAR_INIT macro to iob_lib.vh;
- change some default values in if_gen.py;
- switch initial for IOB_VAR_INIT for buses stubs in if_gen.py.
=> switch initial for IOB_VAR_INIT for buses stubs in if_gen.py

scripts/iob_sys_builder.py, scripts/mkregs.py, scripts/verilog2tex.py
- remove dummy imports from mkregs.py;
- add iob_sys_builder.py.
=> towards iob_sys_builder

hardware/apb2iob/hw_setup.mk, hardware/axil2iob/hw_setup.mk, hardware/iob2apb/hw_setup.mk, hardware/iob2axil/hw_setup.mk, hardware/iob2axis/hw_setup.mk, scripts/version.py, setup.mk
Generate files directly in build directory instead of in the root setup directory followed by a file copy.
=> feat(build-lib): generate files directly in build directory

scripts/blocks.py, scripts/ios.py, scripts/setup.py, scripts/submodule_utils.py
- Add functions useful for IOb-SoC setup.py
- Make regs optional
=> feat(build-lib): Modifications for building IOb-SoC systems

scripts/mk_configuration.py
- Replace Verilog syntax found in macros by corresponding C syntax.
=> feat(version): Fix software macros

scripts/mk_configuration.py, scripts/setup.py
- Auto-add `iob_s_port.vh` and `cpu_iob_s_portmap.vh` to hardware headers list
=> feat(headers): Auto-add iob_s_port.vh and cpu_iob_s_portmap.vh 

scripts/build_srcs.py
With these modifications, the `modules` lists from the `submodules['*_setup']['modules']` in the `*_setup.py` file, accept optional parameters along with LIB modules [similar to what is already done for 'submodules']. 
The format for passing parameters is a python tuple, where the second argument is the parameter: 
```('<module_name>',<parameter_obj>)```
The `<parameter_obj>` may be any python object, including a list of parameters.
The imported module can access the `<parameter_obj>` passed, via the variable named `module_parameters`.
For example, if we set the `modules` list as: `submodules['hw_setup']['modules']= [ ('iob_fifo_sync', (4,8)) ]` The `iob_fifo_sync.py` python module will receive a variable named `module_parameters` with the value `(4,8)`.
If we want to manipulate the …
=> feat(parameters): Add support for LIB module python parameters

scripts/submodule_utils.py
- Ensure `string` variable is a string. (It may be an integer sometimes,
so convert it)
=> feat(submodule_utils): Fix regex in submodule_utils

scripts/if_gen.py
Grouped repeated code in functions
Removed usage of macros
=> [if_gen] improved file generation

build.mk, hardware/fpga/quartus/build.tcl, hardware/fpga/vivado/build.tcl
- Import `.vqm` and `verilog` IPs in `build.tcl`
- Update `$(BSP_H)` target to copy files only if they exist. Otherwise create an empty `bsp.h` file.
=> Import `.vqm` and `verilog` IPs in `build.tcl`; Fix `BSP_H` target.

software/python/board_client.py, software/python/board_server.py, software/python/iob_colors.py
- Update `board_client.py` and `board_server.py` to version `V0.2`.
- Add `iob_colors.py` as it is required by the new `board_client.py`
=> feat(python): Update board scripts

scripts/ios.py
This commit fixes a bug finding the last comma of the file. The bug would cause infinite loops trying to find the last comma, when the last line did not contain one (for example, when the line had a macro).
=> feat(ios.py): Fix bug in delete_last_comma() function.

scripts/mkregs.py, setup.mk
- update swreg_gen.v file generation to be formattable by verible
- include *swreg_gen.v files in verible format target
=> Fix swreg gen

scripts/submodule_utils.py
- Update regex of script that parses signals generated by `if_gen.py`, as new signals may not have a comment at the end.
=> feat(submodule_utils.py): Update signal format parser for `if_gen.py`

scripts/mkregs.py
Also gave color to the ERROR messages.
=> mkregs.py: support 8 Bytes registers.

scripts/black_format.py, scripts/clang_format.py
- update format scripts to handle execution without finding files with respective extentions
=> fix(format): format scripts without found files

scripts/default.nix
- add python `matplotlib` and `scipy` packages to draw plots and scientific calculations
- required for iobundle projects
=> feat(nix): add python packages

scripts/sw_format.py
- minor fixes to sw format: 
- improve comments 
- use `path` in scope instead of `args.path`
=> fix(format): minor changes to sw format

scripts/mkregs.py, scripts/submodule_utils.py
[eval_param_expression] fixed not replacing parameters recursively
=> [mkregs] fixed ports and portmaps

scripts/if_gen.py, scripts/iob_module.py, scripts/mkregs.py, scripts/verilog_tools.py
[verilog_tools] fixed substrings being found in snippet file name
[if_gen] ports with size=1 dont need part select
=> [iob_module] fixed missing files with different purposes

scripts/verilog-lint.py, scripts/verilog_tools.py
[tools] added break to avoid duplicated snippets
=> [lint] added --time flag.

hardware/modules/apb2iob/hardware/src/apb2iob.v, hardware/modules/iob2apb/hardware/src/iob2apb.v, hardware/modules/iob2axil/hardware/src/iob2axil.vt, hardware/modules/iob_split_v2/hardware/src/iob_split2.v, scripts/iob_module.py
- update iob_module to generate `iob_s_port` and `iob_s_s_portmap` using
dictionaries
- update interface filenames without `iob_` prefix
=> fix(if_gen): update interface generation

hardware/modules/iob_aoi/iob_aoi.py, scripts/iob_wire.py
Here I created a new file in the scripts folder named iob_wire.py witch contains the new iob_wire class with name and bit_width as attributes.
Also fixed a typo in the file iob_aoi.py that was importing the add module instead of the and module.
Should I do separate PRs?
=> iob_wire class

hardware/modules/iob_and/hardware/src/iob_and.v, hardware/modules/iob_aoi/hardware/simulation/src/iob_aoi_tb.v, hardware/modules/iob_inv/hardware/src/iob_inv.v, hardware/modules/iob_or/hardware/src/iob_or.v, hardware/modules/iob_xor/hardware/src/iob_xor.v
Made a test bench for the `iob_aoi` module that displays all possible combinations of the input and the resulting output.
The results where as expected.
Also finished removing the warnings from `iob_and` `iob_or` and `iob_xor`.
=> Made a tb for `iob_aoi`

hardware/modules/fifo/iob_fifo_async/hardware/src/iob_fifo_async.v, hardware/modules/iob_utils.vh, hardware/modules/regfile/iob_regfile_2p/hardware/src/iob_regfile_2p.v, scripts/mkregs.py
[regfile_2p] removed unused iob_utils.vh
=> [mkregs][fifo_async] fixed port order

hardware/simulation/xcelium.mk, scripts/build_srcs.py
[build_srcs] removed deprecated IOB_CORE_NAME
=> [cov] fixed top

hardware/modules/counter/iob_modcnt/iob_modcnt.py
- update iob_modcnt to use correct counter_ld module
=> fix(modcnt): use correct counter

hardware/modules/acc/iob_acc_ld/hardware/src/iob_acc_ld.v, hardware/modules/div/iob_div_subshift/hardware/src/iob_div_subshift.v, hardware/modules/fifo/iob_fifo_async/hardware/src/iob_fifo_async.v, hardware/modules/ram/iob_ram_2p/hardware/src/iob_ram_2p.v, hardware/modules/ram/iob_ram_t2p/hardware/src/iob_ram_t2p.v, hardware/modules/rom/iob_rom_dp/hardware/src/iob_rom_dp.v
- update some LIB modules to remove some Spyglass warnings
=> feat(lint): remove Spyglass warnings

scripts/latex.py
Unecessary enclosing parenthesis are now removed before printing to tex
=> [latex.py] clog2 is now converted to log_2.

hardware/syn/Makefile
- update synthesis makefile to set DESIGN to NAME - NAME_CSR_IF logic was merged into NAME (top level)
=> fix(syn): set design to NAME, NAME_CSR_IF removed
